apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaggibuggy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaggibuggy
  template:
    metadata:
      labels:
        app: jaggibuggy
    spec:
      containers:
      - name: jaggibuggy
        image: 339656718719.dkr.ecr.us-west-2.amazonaws.com/jaggiimages
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaggibuggy
    k8s-app: jaggibuggy
  name: jaggibuggy
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: jaggibuggy
